using TinyValidations.SourceGen.Emission.Contributions;
using TinyValidations.SourceGen.Emission.Runners;
using TinyValidations.SourceGen.Emission.Writing;
using TinyValidations.SourceGen.Planning;

namespace TinyValidations.SourceGen.Emission.Source
{
    internal sealed class GeneratedSourceEmitter
    {
        private readonly ValidationContributionMetadataEmitter _metadataEmitter = new ValidationContributionMetadataEmitter();
        private readonly ValidationRunnerEmitter _runnerEmitter = new ValidationRunnerEmitter();
        private readonly ValidationContributionEmitter _contributionEmitter = new ValidationContributionEmitter();
        private readonly ModuleInitializerEmitter _moduleInitializerEmitter = new ModuleInitializerEmitter();

        public string Emit(GeneratedValidationPlan plan)
        {
            var writer = new SourceWriter();

            writer.WriteLine("// <auto-generated />");
            writer.WriteLine("using System.Linq;");
            writer.WriteLine("using Microsoft.Extensions.DependencyInjection;");
            writer.WriteLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            writer.WriteLine();
            _metadataEmitter.Emit(plan, writer);
            writer.WriteLine();
            writer.WriteLine("namespace TinyValidations.Generated");
            writer.OpenBlock();

            foreach (var runner in plan.Runners)
            {
                _runnerEmitter.Emit(runner, writer);
                writer.WriteLine();
            }

            _contributionEmitter.Emit(plan, writer);
            writer.WriteLine();
            _moduleInitializerEmitter.Emit(writer);
            writer.CloseBlock();

            return writer.ToString();
        }
    }
}
